import AppKit
import CoreGraphics
import Foundation
import os.log

/// Spritesheet loader for the pet pixel art. The packed sheet and its JSON
/// metadata are generated by `tools/sprites/build_sprites.sh` from
/// `tools/sprites/gen_pet.lua`, then committed under
/// `NotchPet/Assets/Sprites/` as a build-time resource.
///
/// At init the library slices every tagged animation into `[CGImage]`
/// frames so `PetView` can fetch a frame in O(1) per draw without any
/// CoreGraphics work on the hot path.
@MainActor
final class PetSpriteLibrary {
    static let shared = PetSpriteLibrary()

    /// Tag name → ordered CGImage frames. Keys follow the `<stage>_<mode>`
    /// convention used by `gen_pet.lua` (e.g. `"adult_happy"`).
    private let framesByTag: [String: [CGImage]]

    /// Fallback image returned when the library fails to load. Kept as a
    /// last-resort 1x1 transparent pixel so `PetView` never crashes.
    private static let fallback: CGImage = {
        let cs = CGColorSpaceCreateDeviceRGB()
        let ctx = CGContext(
            data: nil,
            width: 1,
            height: 1,
            bitsPerComponent: 8,
            bytesPerRow: 4,
            space: cs,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        )!
        return ctx.makeImage()!
    }()

    private init() {
        self.framesByTag = Self.load()
    }

    // MARK: - Loading

    private static func load() -> [String: [CGImage]] {
        let log = OSLog(subsystem: "com.notchpet.NotchPet", category: "PetSprite")
        guard
            let pngURL = Bundle.main.url(forResource: "pet", withExtension: "png", subdirectory: "Sprites"),
            let jsonURL = Bundle.main.url(forResource: "pet", withExtension: "json", subdirectory: "Sprites")
        else {
            os_log(.error, log: log, "PetSprite: sheet assets not found in bundle")
            return [:]
        }

        guard
            let nsImage = NSImage(contentsOf: pngURL),
            let sheet = nsImage.cgImage(forProposedRect: nil, context: nil, hints: nil)
        else {
            os_log(.error, log: log, "PetSprite: failed to decode %{public}@", pngURL.path)
            return [:]
        }

        let jsonData: Data
        do {
            jsonData = try Data(contentsOf: jsonURL)
        } catch {
            os_log(.error, log: log, "PetSprite: failed to read json: %{public}@", String(describing: error))
            return [:]
        }

        let decoded: AsepriteSheet
        do {
            decoded = try JSONDecoder().decode(AsepriteSheet.self, from: jsonData)
        } catch {
            os_log(.error, log: log, "PetSprite: failed to decode json: %{public}@", String(describing: error))
            return [:]
        }

        // Slice one CGImage per source frame in emission order. The packed
        // sheet de-duplicates byte-identical frames, so multiple source
        // frames may share the same rect — the per-source-frame crop keeps
        // tag `from...to` lookups O(1).
        var sliced: [CGImage] = []
        sliced.reserveCapacity(decoded.frames.count)
        for entry in decoded.frames {
            let r = entry.frame
            let cropRect = CGRect(x: r.x, y: r.y, width: r.w, height: r.h)
            if let sub = sheet.cropping(to: cropRect) {
                sliced.append(sub)
            } else {
                sliced.append(fallback)
            }
        }

        var byTag: [String: [CGImage]] = [:]
        byTag.reserveCapacity(decoded.meta.frameTags.count)
        for tag in decoded.meta.frameTags {
            guard tag.from >= 0, tag.to < sliced.count, tag.to >= tag.from else { continue }
            let range = tag.from...tag.to
            byTag[tag.name] = Array(sliced[range])
        }
        os_log(.info, log: log, "PetSprite: loaded %d tags, %d source frames", byTag.count, sliced.count)
        return byTag
    }

    // MARK: - Public API

    /// Fetch a single animation frame.
    ///
    /// Species-aware tag conventions:
    /// - `<species>_egg_idle`
    /// - `<species>_child_<mode>` (pre-personality; uses cheerful expression)
    /// - `<species>_<personality>_<stage>_<mode>` for adult / elder
    /// - `<species>_departed_idle`
    ///
    /// Fallback chain: exact → personality idle → cheerful same mode →
    /// cheerful idle → chick cheerful adult idle → 1x1 transparent.
    func frame(
        species: Species,
        stage: LifecycleStage,
        mode: PetMode,
        personality: PersonalityTrait?,
        frameIndex: Int
    ) -> CGImage {
        let keys = Self.fallbackKeys(species: species, stage: stage, mode: mode, personality: personality)
        for key in keys {
            if let frames = framesByTag[key], !frames.isEmpty {
                let i = ((frameIndex % frames.count) + frames.count) % frames.count
                return frames[i]
            }
        }
        return Self.fallback
    }

    private static func fallbackKeys(
        species: Species,
        stage: LifecycleStage,
        mode: PetMode,
        personality: PersonalityTrait?
    ) -> [String] {
        let sp = species.rawValue
        var keys: [String] = []
        switch stage {
        case .egg:
            keys.append("\(sp)_egg_idle")
        case .departed:
            keys.append("\(sp)_departed_idle")
        case .child:
            keys.append("\(sp)_child_\(mode.tagName)")
            keys.append("\(sp)_child_idle")
        case .adult, .elder:
            let stagePart = (stage == .adult) ? "adult" : "elder"
            let pers = personality?.tagName ?? "cheerful"
            keys.append("\(sp)_\(pers)_\(stagePart)_\(mode.tagName)")
            keys.append("\(sp)_\(pers)_\(stagePart)_idle")
            keys.append("\(sp)_cheerful_\(stagePart)_\(mode.tagName)")
            keys.append("\(sp)_cheerful_\(stagePart)_idle")
            keys.append("\(sp)_cheerful_adult_idle")
        }
        // Ultimate catch-all
        keys.append("chick_cheerful_adult_idle")
        keys.append("chick_egg_idle")
        return keys
    }
}

// MARK: - Aseprite JSON schema

private struct AsepriteRect: Decodable {
    let x: Int
    let y: Int
    let w: Int
    let h: Int
}

private struct AsepriteFrameEntry: Decodable {
    let frame: AsepriteRect
    let duration: Int
}

private struct AsepriteTag: Decodable {
    let name: String
    let from: Int
    let to: Int
}

private struct AsepriteMeta: Decodable {
    let frameTags: [AsepriteTag]
}

private struct AsepriteSheet: Decodable {
    let frames: [AsepriteFrameEntry]
    let meta: AsepriteMeta
}
