import AVFoundation
import Foundation
import os.log

/// Lightweight wrapper around `AVAudioPlayer`. All gameplay SFX are
/// pre-loaded at launch; each `play(_:)` call plays through the
/// standard audio output at system volume.
///
/// Files live at `NotchPet/Assets/Audio/*.wav`, generated by
/// `tools/sprites/gen_sounds.py` and bundled via xcodegen's
/// `resources:` entry.
///
/// Callers are expected to invoke `play(_:)` from `@MainActor` (all
/// current call sites satisfy this). Internally the actual
/// `AVAudioPlayer.play()` is dispatched to a background serial queue
/// so CoreAudio stalls — first play after a Bluetooth route change
/// or HW wake can take seconds — never block the caller.
@MainActor
final class SoundPlayer {
    static let shared = SoundPlayer()

    enum Sound: String, CaseIterable {
        case feed
        case play
        case rest
        case hatch
        case depart
        case happy
        /// Block 5: played when an aloof pet refuses a feed.
        case feedReject
        /// Block 5: played when a grumpy pet flips to `.angry`.
        case angry
        /// Block 6: played when medicine is administered.
        case medicine
        /// Block 6: played when poop is cleaned.
        case clean
        /// Critical warning — five-second two-tone emergency siren
        /// fired by `PetState.maintainCriticalWarning()` while the
        /// pet is deep into any death countdown (≥60% through the
        /// hunger / happy / sick threshold). Loud on purpose; the
        /// whole point is to pull the user's attention away from
        /// whatever they're doing before the pet dies.
        case danger
    }

    private let log = OSLog(subsystem: "com.notchpet.NotchPet", category: "SoundPlayer")
    /// All `AVAudioPlayer` mutation flows through this queue so a
    /// `play()` stall (CoreAudio HW wake-up, Bluetooth re-route, …)
    /// never blocks the thread that called it. Serial so two rapid
    /// play() calls on the same sound still reset `currentTime` in
    /// the expected order.
    private let ioQueue = DispatchQueue(
        label: "com.notchpet.soundplayer.io",
        qos: .userInitiated
    )
    /// Only ever touched from `ioQueue` after init — safe to read
    /// without locks because init runs to completion before any
    /// `play()` call.
    private var players: [Sound: AVAudioPlayer] = [:]

    private init() {
        for sound in Sound.allCases {
            guard let url = Bundle.main.url(
                forResource: sound.rawValue,
                withExtension: "wav",
                subdirectory: "Audio"
            ) else {
                os_log(.error, log: log, "SoundPlayer: missing %{public}@", sound.rawValue)
                continue
            }
            do {
                let player = try AVAudioPlayer(contentsOf: url)
                player.prepareToPlay()
                players[sound] = player
            } catch {
                os_log(.error, log: log, "SoundPlayer: failed to load %{public}@: %{public}@", sound.rawValue, error.localizedDescription)
            }
        }
        os_log(.info, log: log, "SoundPlayer: loaded %d sounds", players.count)
    }

    /// Non-blocking play — dispatches the actual `AVAudioPlayer.play()`
    /// call onto `ioQueue` so the caller (main actor) returns
    /// immediately even if CoreAudio stalls during HW wake / BT route.
    func play(_ sound: Sound) {
        let volume = AppSettings.shared.soundVolume
        guard volume > 0, let player = players[sound] else { return }
        let localLog = log
        ioQueue.async {
            player.volume = volume
            if player.isPlaying {
                player.currentTime = 0
            }
            player.play()
            os_log(.info, log: localLog, "SoundPlayer: played %{public}@", sound.rawValue)
        }
    }
}
