import AVFoundation
import Foundation
import os.log

/// Lightweight wrapper around `AVAudioPlayer`. All gameplay SFX are
/// pre-loaded at launch; each `play(_:)` call plays through the
/// standard audio output at system volume.
///
/// Files live at `NotchPet/Assets/Audio/*.wav`, generated by
/// `tools/sprites/gen_sounds.py` and bundled via xcodegen's
/// `resources:` entry.
@MainActor
final class SoundPlayer {
    static let shared = SoundPlayer()

    enum Sound: String, CaseIterable {
        case feed
        case play
        case rest
        case hatch
        case depart
        case happy
        /// Block 5: played when an aloof pet refuses a feed.
        case feedReject
        /// Block 5: played when a grumpy pet flips to `.angry`.
        case angry
        /// Block 6: played when medicine is administered.
        case medicine
        /// Block 6: played when poop is cleaned.
        case clean
    }

    private let log = OSLog(subsystem: "com.notchpet.NotchPet", category: "SoundPlayer")
    private var players: [Sound: AVAudioPlayer] = [:]

    private init() {
        for sound in Sound.allCases {
            guard let url = Bundle.main.url(
                forResource: sound.rawValue,
                withExtension: "wav",
                subdirectory: "Audio"
            ) else {
                os_log(.error, log: log, "SoundPlayer: missing %{public}@", sound.rawValue)
                continue
            }
            do {
                let player = try AVAudioPlayer(contentsOf: url)
                player.prepareToPlay()
                players[sound] = player
            } catch {
                os_log(.error, log: log, "SoundPlayer: failed to load %{public}@: %{public}@", sound.rawValue, error.localizedDescription)
            }
        }
        os_log(.info, log: log, "SoundPlayer: loaded %d sounds", players.count)
    }

    func play(_ sound: Sound) {
        let volume = AppSettings.shared.soundVolume
        guard volume > 0, let player = players[sound] else { return }
        player.volume = volume
        if player.isPlaying {
            player.currentTime = 0
        }
        player.play()
        os_log(.info, log: log, "SoundPlayer: played %{public}@", sound.rawValue)
    }
}
